BLYNK_AUTH = "L2R-hSjriHAgrhyGmTro5jjEhx_Qd1M6"
SERVER_NAME = "ftm.ddns.net"
SERVER_PORT = 8080

TEMP_PIN = 0
BACKUP_PIN = 1
LOCAL_IP_PIN = 2
UPDATE_PIN = 3
PUBLIC_IP_PIN = 4
RESTART_PIN = 10
SHUTDOWN_PIN = 11